### PR TITLE
implement spring data 4 driver

### LINKED ISSUE #118: JHLite Spring Boot 3 - Mongock compatibility
**Title**
Mongock - Spring Boot 3 compatibility

**Description**
The JHipster team is upgrading JHLite to Spring Boot 3. This ticket is to support / track any issues with checking Mongock's compatibility with Spring Boot 3. 

The reference ticket in JHipster: https://github.com/jhipster/jhipster-lite/issues/3750 

**Priority:** Urgent

### PR DESCRIPTION
**Pull request by atomfrede**
Hope I got your idea correct, to implement a v4 and v3 driver (need to add it here) 🤦 Okay no I see I get it a little wrong. Will adapt and rebase the PR

closes https://github.com/mongock/mongock/issues/583

### CODE REVIEW

**Comment by atomfrede** [comment]
Somehow the rebase looks strange 🤔 But together with the driver it fixes the issues we have at jhipster. Thanks @dieppa for the support and upfront work!

**Comment by dieppa** [comment]
@atomfrede  There may be something JHpster depends on and I missing it, but why do you think we need the springdata v3 here too?

As long as I understand, where you are migrating to Springboot3, implicitly we are assuming that the project uses springdata 4,  right? Or I am missing something here?

If that's the case, my idea is only having here the springboot3 runner and springdata4 driver

**Comment by atomfrede** [comment]
Yes totally right we don't need data-v3 here anymore.

**Comment by dieppa** [comment]
once removed the springdata-v3, I just need to perform a couple of local tests for sanity check and I think it's ready to go

**Comment by atomfrede** [comment]
Should be ready by now. Updated the gh action to use java 17 too

**Comment by dieppa** [comment]
Why do I still the springdata-v3 ? Did you forget to remove it?

**Comment by dieppa** [comment]
sorry, my bad. It's springboot 3...forget about it:)

**Review by dieppa — APPROVED** [review]
LGTM thanks @atomfrede !

**Pull request merged**
